version = 0.1
[default]
[default.global]
[default.global.parameters]
stack_name = "kumo"
region = "us-east-1"

[default.deploy]
[default.deploy.parameters]
s3_bucket = "kumo"
s3_prefix = "sam"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
