AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kumo
  Tropy Web Services Template

Globals:
  Function:
    Runtime: nodejs20.x

Resources:
  ReleasesFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: lib/releases/index.handler
      Description: Tropy release data
      Events:
        ReleaseChannel:
          Type: HttpApi
          Properties:
            Path: /releases/{channel}
            Method: get
  UpdateFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: lib/update/index.handler
      Description: Tropy update service
      Events:
        AutoUpdate:
          Type: HttpApi
          Properties:
            Path: /update/{channel}/{platform}/{arch}/{version}
            Method: get
        AutoUpdateX64:
          Type: HttpApi
          Properties:
            Path: /update/{channel}/{platform}/{version}
            Method: get
